name: Download Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull and Save Docker Image
      run: |
        docker pull gnina/gnina:latest
        docker save -o gnina.tar gnina/gnina:latest
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-docker-image
        path: gnina.tar
